backend:
  name: github
  repo: vih-elevforening/elevforeningen-jekyll
  branch: gh-pages # Branch to update (optional; defaults to master)

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "author", name: "author", widget: "string"}      
      - {label: "Category", name: "category", widget: "select", options: ["Gensynsweekend", "Generalforsamling", "Nyhedsbrev"]}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Excerpt", name: "intro", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Intro", name: "intro", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Layout", name: "layout", widget: "select", options: ["page", "blog", "default"]}
      - {label: "Show headline", name: "show_headline", widget: "select", options: ["true", "false"], required: false}
      - {label: "Body", name: "body", widget: "markdown",  required: false}
  - name: "index" # Used in routes, e.g., /admin/collections/blog
    label: "Homepage" # Used in the UI
    files: 
      - file: "index.md"
        name: "homepage"
        label: "Homepage"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "string"}
          - {label: "Layout", name: "layout", widget: "select", options: ["page", "blog", "default"]}
          - {label: "Show headline", name: "show_headline", widget: "select", options: ["true", "false"]}
          - {label: "Body", name: "body", widget: "markdown"}   
